# Generated by Django 4.2.30 on 2026-09-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('excerpt', models.CharField(blank=True, max_length=255, verbose_name='Excerpt')),
                ('body', models.TextField()),
                ('icon', models.CharField(max_length=20, verbose_name='Icon')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
