# Generated by Django 4.2.30 on 2026-09-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('anons', models.CharField(blank=True, max_length=255, verbose_name='Anons')),
                ('full_text', models.TextField()),
                ('author', models.CharField(default='Anonymous', max_length=100, verbose_name='Author')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
